name: Tests unit

on: [push]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm

      - name: Runing primsa generate
        run: pnpm db:generate

      - name: Run tests
        run: pnpm test:unit
